### PR TITLE
Updated socket.io-client from 1.2.1 to 1.3.7

### PR DESCRIPTION
**Pull request by luislobo**
Updated socket.io-client from 1.2.1 to 1.3.7
Current sails uses ^1.3.7

### CODE REVIEW

**Comment by luislobo** [comment]
@tjwebb besides the unit tests, I have run it using our application and it works.

**Comment by luislobo** [comment]
@sgress454 any comments on this? should we merge it? we are using 1.3.7 server side already

**Comment by luislobo** [comment]
@mikermcneil can you check this please? server side sails is using 1.3.7, while the client is still using 1.2.1

**Comment by sgress454** [comment]
Thanks @luislobo, I'll take a look now and make sure the tests all pass w/ 1.3.7.

**Comment by sgress454** [comment]
Oops, got a little ahead of myself--I published a new version of sails.io.js with the new socket.io-client bundled, but forgot to merge your PR in first.  Please note that the socket.io-client _dependency_ in this package only affects the tests; at present there's nothing in the automated build script that takes that dependency and creates `dependencies/socket.io.min.js` out of it (that would be a great PR for somebody).  Anyway, I'll merge everything together now and close this.  Thanks again @luislobo!

**Comment by luislobo** [comment]
Yeah I think I did modify the dist file too. Great you merged it!                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: sgress454Sent: lunes, 21 de diciembre de 2015 01:40 p.m.To: balderdashy/sails.io.jsReply To: balderdashy/sails.io.jsCc: Luis Lobo BorobiaSubject: Re: [sails.io.js] Updated socket.io-client from 1.2.1 to 1.3.7 (#76)Oops, got a little ahead of myself--I published a new version of sails.io.js with the new socket.io-client bundled, but forgot to merge your PR in first.  Please note that the socket.io-client dependency in this package only affects the tests; at present there's nothing in the automated build script that takes that dependency and creates dependencies/socket.io.min.js out of it (that would be a great PR for somebody).  Anyway, I'll merge everything together now and close this.  Thanks again @luislobo!

—Reply to this email directly or view it on GitHub.

**Pull request merged**
