### PR TITLE
Fix Browserify and JSPM

### PR DESCRIPTION
**Pull request by Mordred**
Inspired by #22

### CODE REVIEW

**Comment by nrempel** [comment]
This is something that should be fixed in the request package, not in this library.

See https://github.com/webpack/react-starter/issues/3#issuecomment-53395089

You can workaround the issue in your build by adding the following config to your webpack config file:

```
  node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  }
```

**Comment by Mordred** [comment]
You are right for `webpack`, but `jspm` tries to load `request` even if it is never used in the browser.

**Comment by nrempel** [comment]
Ah yes, you are right.

**Comment by sgress454** [comment]
Re: this and #22, is the problem just that the bundlers see `require()` and try to do something with it?  Because for the life of me I can't see in what circumstances the code in question would actually run, ever.  Either `window` is undefined, in which case `xOrigin` will be undefined, and the code requiring `request` won't be run, or `window` is _not_ undefined, in which case the `jsonp` call will be made, and again, the `request` code will never be run.   What's more, I don't see what the code would accomplish even if it _did_ run, since it's not saving a cookie anywhere that `socket.io` would have access to it.  So really, I think we can just remove that code entirely and solve all these problems.  I'll check in with @mikermcneil to see if our former selves had some brilliant idea here.

**Comment by sgress454** [comment]
Ok -- removed calls to request in https://github.com/balderdashy/sails.io.js/commit/a23cc5bc0384c8c15b16b9197d763e1ea7a2ea0d and published v0.13.7.

**Comment by nrempel** [comment]
Thank you! Even better. 😄

**Pull request closed without merging**
