### PR TITLE
Add rejectUnauthorized to the settable options for socket connections.

### PR DESCRIPTION
**Pull request by ksylvan**
This fixes https://github.com/balderdashy/sails.io.js/issues/102

### CODE REVIEW

**Comment by kapouer** [comment]
Not that i directly care, but to get that PR accepted you should restrict the commit to only what you propose to do. No whitespaces fixing, no reordering of SOCKET_OPTIONS.

**Comment by ksylvan** [comment]
Did that. CI checks are failing, though it works well in my environment.

**Comment by ksylvan** [comment]
Original poster of https://github.com/balderdashy/sails.io.js/issues/102 verified that his problem is fixed by this PR.

**Comment by mrvini** [comment]
@ksylvan , any updates on this merge request? are tests failing because new option missing from https://github.com/balderdashy/sails.io.js/blob/master/test/helpers/lifecycle.js#L103

**Comment by ksylvan** [comment]
No updates. Tests are failing because of something unrelated. Looks like that test has been failing on sails-0.10 for a few previous commits too.

**Comment by sgress454** [comment]
I can ignore the test failure; as seems to happen with Travis, an older version of Node just started failing one day after an unrelated commit.  It passes for me locally with v0.10.x.  

I'd love for there to be a test that actually _demonstrates_ the problem that this solves, but setting up SSL tests is a bigger job that we should be undertaking separately anyway.  And, adding an allowable option to the `SOCKET_OPTIONS` array is not exactly a dangerous proposition, so I'll take y'alls word for it.

**Comment by ksylvan** [comment]
Thanks. When is the next release of sails.io.js that will include this?

**Comment by ksylvan** [comment]
@sgress454 Thanks for merging this. When is the next scheduled release of sails.io.js for npm?

**Comment by sgress454** [comment]
@ksylvan Just published 0.13.8!

**Comment by ksylvan** [comment]
@sgress454 Thank you very much!

**Pull request merged**
